export const countriesWithCode = [
    {
      name: "Afghanistan",
      flag: "🇦🇫",
      code: "AF",
      dial_code: "+93",
      phone_number_length: 9,
    },
    {
      name: "Åland Islands",
      flag: "🇦🇽",
      code: "AX",
      dial_code: "+358",
      phone_number_length: 9,
    },
    {
      name: "Albania",
      flag: "🇦🇱",
      code: "AL",
      dial_code: "+355",
      phone_number_length: 9,
    },
    {
      name: "Algeria",
      flag: "🇩🇿",
      code: "DZ",
      dial_code: "+213",
      phone_number_length: 9,
    },
    {
      name: "American Samoa",
      flag: "🇦🇸",
      code: "AS",
      dial_code: "+1684",
      phone_number_length: 7,
    },
    {
      name: "Andorra",
      flag: "🇦🇩",
      code: "AD",
      dial_code: "+376",
      phone_number_length: 6,
    },
    {
      name: "Angola",
      flag: "🇦🇴",
      code: "AO",
      dial_code: "+244",
      phone_number_length: 9,
    },
    {
      name: "Anguilla",
      flag: "🇦🇮",
      code: "AI",
      dial_code: "+1-264",
      phone_number_length: 7,
    },
    {
      name: "Antarctica",
      flag: "🇦🇶",
      code: "AQ",
      dial_code: "+672",
      phone_number_length: 9,
    },
    {
      name: "Antigua and Barbuda",
      flag: "🇦🇬",
      code: "AG",
      dial_code: "+1-268",
      phone_number_length: 7,
    },
    {
      name: "Argentina",
      flag: "🇦🇷",
      code: "AR",
      dial_code: "+54",
      phone_number_length: 10,
    },
    {
      name: "Armenia",
      flag: "🇦🇲",
      code: "AM",
      dial_code: "+374",
      phone_number_length: 8,
    },
    {
      name: "Aruba",
      flag: "🇦🇼",
      code: "AW",
      dial_code: "+297",
      phone_number_length: 7,
    },
    {
      name: "Australia",
      flag: "🇦🇺",
      code: "AU",
      dial_code: "+61",
      phone_number_length: 9,
    },
    {
      name: "Austria",
      flag: "🇦🇹",
      code: "AT",
      dial_code: "+43",
      phone_number_length: 9,
    },
    {
      name: "Azerbaijan",
      flag: "🇦🇿",
      code: "AZ",
      dial_code: "+994",
      phone_number_length: 9,
    },
    {
      name: "Bahamas",
      flag: "🇧🇸",
      code: "BS",
      dial_code: "+1-242",
      phone_number_length: 7,
    },
    {
      name: "Bahrain",
      flag: "🇧🇭",
      code: "BH",
      dial_code: "+973",
      phone_number_length: 8,
    },
    {
      name: "Bangladesh",
      flag: "🇧🇩",
      code: "BD",
      dial_code: "+880",
      phone_number_length: 11,
    },
    {
      name: "Barbados",
      flag: "🇧🇧",
      code: "BB",
      dial_code: "+1-246",
      phone_number_length: 7,
    },
    {
      name: "Belarus",
      flag: "🇧🇾",
      code: "BY",
      dial_code: "+375",
      phone_number_length: 9,
    },
    {
      name: "Belgium",
      flag: "🇧🇪",
      code: "BE",
      dial_code: "+32",
      phone_number_length: 9,
    },
    {
      name: "Belize",
      flag: "🇧🇿",
      code: "BZ",
      dial_code: "+501",
      phone_number_length: 7,
    },
    {
      name: "Benin",
      flag: "🇧🇯",
      code: "BJ",
      dial_code: "+229",
      phone_number_length: 8,
    },
    {
      name: "Bermuda",
      flag: "🇧🇲",
      code: "BM",
      dial_code: "+1-441",
      phone_number_length: 7,
    },
    {
      name: "Bhutan",
      flag: "🇧🇹",
      code: "BT",
      dial_code: "+975",
      phone_number_length: 8,
    },
    {
      name: "Bolivia",
      flag: "🇧🇴",
      code: "BO",
      dial_code: "+591",
      phone_number_length: 8,
    },
    {
      name: "Bosnia and Herzegovina",
      flag: "🇧🇦",
      code: "BA",
      dial_code: "+387",
      phone_number_length: 8,
    },
    {
      name: "Botswana",
      flag: "🇧🇼",
      code: "BW",
      dial_code: "+267",
      phone_number_length: 7,
    },
    {
      name: "Brazil",
      flag: "🇧🇷",
      code: "BR",
      dial_code: "+55",
      phone_number_length: 11,
    },
    {
      name: "British Indian Ocean Territory",
      flag: "🇮🇴",
      code: "IO",
      dial_code: "+246",
      phone_number_length: 7,
    },
    {
      name: "Brunei Darussalam",
      flag: "🇧🇳",
      code: "BN",
      dial_code: "+673",
      phone_number_length: 7,
    },
    {
      name: "Bulgaria",
      flag: "🇧🇬",
      code: "BG",
      dial_code: "+359",
      phone_number_length: 8,
    },
    {
      name: "Burkina Faso",
      flag: "🇧🇫",
      code: "BF",
      dial_code: "+226",
      phone_number_length: 8,
    },
    {
      name: "Burundi",
      flag: "🇧🇮",
      code: "BI",
      dial_code: "+257",
      phone_number_length: 8,
    },
    {
      name: "Cambodia",
      flag: "🇰🇭",
      code: "KH",
      dial_code: "+855",
      phone_number_length: 8,
    },
    {
      name: "Cameroon",
      flag: "🇨🇲",
      code: "CM",
      dial_code: "+237",
      phone_number_length: 8,
    },
    {
      name: "Canada",
      flag: "🇨🇦",
      code: "CA",
      dial_code: "+1",
      phone_number_length: 10,
    },
    {
      name: "Cape Verde",
      flag: "🇨🇻",
      code: "CV",
      dial_code: "+238",
      phone_number_length: 7,
    },
    {
      name: "Cayman Islands",
      flag: "🇰🇾",
      code: "KY",
      dial_code: "+1-345",
      phone_number_length: 7,
    },
    {
      name: "Central African Republic",
      flag: "🇨🇫",
      code: "CF",
      dial_code: "+236",
      phone_number_length: 8,
    },
    {
      name: "Chad",
      flag: "🇹🇩",
      code: "TD",
      dial_code: "+235",
      phone_number_length: 8,
    },
    {
      name: "Chile",
      flag: "🇨🇱",
      code: "CL",
      dial_code: "+56",
      phone_number_length: 9,
    },
    {
      name: "China",
      flag: "🇨🇳",
      code: "CN",
      dial_code: "+86",
      phone_number_length: 11,
    },
    {
      name: "Christmas Island",
      flag: "🇨🇽",
      code: "CX",
      dial_code: "+61",
      phone_number_length: 9,
    },
    {
      name: "Cocos (Keeling) Islands",
      flag: "🇨🇨",
      code: "CC",
      dial_code: "+61",
      phone_number_length: 9,
    },
    {
      name: "Colombia",
      flag: "🇨🇴",
      code: "CO",
      dial_code: "+57",
      phone_number_length: 10,
    },
    {
      name: "Comoros",
      flag: "🇰🇲",
      code: "KM",
      dial_code: "+269",
      phone_number_length: 8,
    },
    {
      name: "Cook Islands",
      flag: "🇨🇰",
      code: "CK",
      dial_code: "+682",
      phone_number_length: 7,
    },
    {
      name: "Costa Rica",
      flag: "🇨🇷",
      code: "CR",
      dial_code: "+506",
      phone_number_length: 8,
    },
    {
      name: "Croatia",
      flag: "🇭🇷",
      code: "HR",
      dial_code: "+385",
      phone_number_length: 9,
    },
    {
      name: "Cuba",
      flag: "🇨🇺",
      code: "CU",
      dial_code: "+53",
      phone_number_length: 8,
    },
    {
      name: "Curaçao",
      flag: "🇨🇼",
      code: "CW",
      dial_code: "+599",
      phone_number_length: 9,
    },
    {
      name: "Cyprus",
      flag: "🇨🇾",
      code: "CY",
      dial_code: "+357",
      phone_number_length: 8,
    },
    {
      name: "Czech Republic",
      flag: "🇨🇿",
      code: "CZ",
      dial_code: "+420",
      phone_number_length: 9,
    },
    {
      name: "Democratic Republic of the Congo",
      flag: "🇨🇩",
      code: "CD",
      dial_code: "+243",
      phone_number_length: 9,
    },
    {
      name: "Denmark",
      flag: "🇩🇰",
      code: "DK",
      dial_code: "+45",
      phone_number_length: 8,
    },
    {
      name: "Djibouti",
      flag: "🇩🇯",
      code: "DJ",
      dial_code: "+253",
      phone_number_length: 8,
    },
    {
      name: "Dominica",
      flag: "🇩🇲",
      code: "DM",
      dial_code: "+1-767",
      phone_number_length: 7,
    },
    {
      name: "Dominican Republic",
      flag: "🇩🇴",
      code: "DO",
      dial_code: "+1-809",
      phone_number_length: 10,
    },
    {
      name: "Ecuador",
      flag: "🇪🇨",
      code: "EC",
      dial_code: "+593",
      phone_number_length: 9,
    },
    {
      name: "Egypt",
      flag: "🇪🇬",
      code: "EG",
      dial_code: "+20",
      phone_number_length: 10,
    },
    {
      name: "El Salvador",
      flag: "🇸🇻",
      code: "SV",
      dial_code: "+503",
      phone_number_length: 8,
    },
    {
      name: "Equatorial Guinea",
      flag: "🇬🇶",
      code: "GQ",
      dial_code: "+240",
      phone_number_length: 9,
    },
    {
      name: "Eritrea",
      flag: "🇪🇷",
      code: "ER",
      dial_code: "+291",
      phone_number_length: 7,
    },
    {
      name: "Estonia",
      flag: "🇪🇪",
      code: "EE",
      dial_code: "+372",
      phone_number_length: 7,
    },
    {
      name: "Eswatini",
      flag: "🇸🇿",
      code: "SZ",
      dial_code: "+268",
      phone_number_length: 8,
    },
    {
      name: "Ethiopia",
      flag: "🇪🇹",
      code: "ET",
      dial_code: "+251",
      phone_number_length: 9,
    },
    {
      name: "Fiji",
      flag: "🇫🇯",
      code: "FJ",
      dial_code: "+679",
      phone_number_length: 7,
    },
    {
      name: "Finland",
      flag: "🇫🇮",
      code: "FI",
      dial_code: "+358",
      phone_number_length: 9,
    },
    {
      name: "France",
      flag: "🇫🇷",
      code: "FR",
      dial_code: "+33",
      phone_number_length: 9,
    },
    {
      name: "French Guiana",
      flag: "🇬🇫",
      code: "GF",
      dial_code: "+594",
      phone_number_length: 9,
    },
    {
      name: "French Polynesia",
      flag: "🇵🇫",
      code: "PF",
      dial_code: "+689",
      phone_number_length: 8,
    },
    {
      name: "Gabon",
      flag: "🇬🇦",
      code: "GA",
      dial_code: "+241",
      phone_number_length: 7,
    },
    {
      name: "Gambia",
      flag: "🇬🇲",
      code: "GM",
      dial_code: "+220",
      phone_number_length: 7,
    },
    {
      name: "Georgia",
      flag: "🇬🇪",
      code: "GE",
      dial_code: "+995",
      phone_number_length: 9,
    },
    {
      name: "Germany",
      flag: "🇩🇪",
      code: "DE",
      dial_code: "+49",
      phone_number_length: 10,
    },
    {
      name: "Ghana",
      flag: "🇬🇭",
      code: "GH",
      dial_code: "+233",
      phone_number_length: 9,
    },
    {
      name: "Greece",
      flag: "🇬🇷",
      code: "GR",
      dial_code: "+30",
      phone_number_length: 10,
    },
    {
      name: "Greenland",
      flag: "🇬🇱",
      code: "GL",
      dial_code: "+299",
      phone_number_length: 7,
    },
    {
      name: "Grenada",
      flag: "🇬🇩",
      code: "GD",
      dial_code: "+1-473",
      phone_number_length: 7,
    },
    {
      name: "Guadeloupe",
      flag: "🇬🇵",
      code: "GP",
      dial_code: "+590",
      phone_number_length: 9,
    },
    {
      name: "Guam",
      flag: "🇬🇺",
      code: "GU",
      dial_code: "+1-671",
      phone_number_length: 7,
    },
    {
      name: "Guatemala",
      flag: "🇬🇹",
      code: "GT",
      dial_code: "+502",
      phone_number_length: 8,
    },
    {
      name: "Guernsey",
      flag: "🇬🇬",
      code: "GG",
      dial_code: "+44-1481",
      phone_number_length: 8,
    },
    {
      name: "Guinea",
      flag: "🇬🇳",
      code: "GN",
      dial_code: "+224",
      phone_number_length: 9,
    },
    {
      name: "Guinea-Bissau",
      flag: "🇬🇼",
      code: "GW",
      dial_code: "+245",
      phone_number_length: 8,
    },
    {
      name: "Guyana",
      flag: "🇬🇾",
      code: "GY",
      dial_code: "+592",
      phone_number_length: 7,
    },
    {
      name: "Haiti",
      flag: "🇭🇹",
      code: "HT",
      dial_code: "+509",
      phone_number_length: 8,
    },
    {
      name: "Honduras",
      flag: "🇭🇳",
      code: "HN",
      dial_code: "+504",
      phone_number_length: 8,
    },
    {
      name: "Hungary",
      flag: "🇭🇺",
      code: "HU",
      dial_code: "+36",
      phone_number_length: 9,
    },
    {
      name: "Iceland",
      flag: "🇮🇸",
      code: "IS",
      dial_code: "+354",
      phone_number_length: 7,
    },
    {
      name: "India",
      flag: "🇮🇳",
      code: "IN",
      dial_code: "+91",
      phone_number_length: 10,
    },
    {
      name: "Indonesia",
      flag: "🇮🇩",
      code: "ID",
      dial_code: "+62",
      phone_number_length: 10,
    },
    {
      name: "Iran",
      flag: "🇮🇷",
      code: "IR",
      dial_code: "+98",
      phone_number_length: 10,
    },
    {
      name: "Iraq",
      flag: "🇮🇶",
      code: "IQ",
      dial_code: "+964",
      phone_number_length: 9,
    },
    {
      name: "Ireland",
      flag: "🇮🇪",
      code: "IE",
      dial_code: "+353",
      phone_number_length: 9,
    },
    {
      name: "Isle of Man",
      flag: "🇮🇲",
      code: "IM",
      dial_code: "+44-1624",
      phone_number_length: 8,
    },
    {
      name: "Israel",
      flag: "🇮🇱",
      code: "IL",
      dial_code: "+972",
      phone_number_length: 9,
    },
    {
      name: "Italy",
      flag: "🇮🇹",
      code: "IT",
      dial_code: "+39",
      phone_number_length: 10,
    },
    {
      name: "Jamaica",
      flag: "🇯🇲",
      code: "JM",
      dial_code: "+1-876",
      phone_number_length: 7,
    },
    {
      name: "Japan",
      flag: "🇯🇵",
      code: "JP",
      dial_code: "+81",
      phone_number_length: 10,
    },
    {
      name: "Jersey",
      flag: "🇯🇪",
      code: "JE",
      dial_code: "+44-1534",
      phone_number_length: 8,
    },
    {
      name: "Kazakhstan",
      flag: "🇰🇿",
      code: "KZ",
      dial_code: "+7",
      phone_number_length: 10,
    },
    {
      name: "Kenya",
      flag: "🇰🇪",
      code: "KE",
      dial_code: "+254",
      phone_number_length: 9,
    },
    {
      name: "Kiribati",
      flag: "🇰🇮",
      code: "KI",
      dial_code: "+686",
      phone_number_length: 7,
    },
    {
      name: "Korea (North)",
      flag: "🇰🇵",
      code: "KP",
      dial_code: "+850",
      phone_number_length: 8,
    },
    {
      name: "Korea (South)",
      flag: "🇰🇷",
      code: "KR",
      dial_code: "+82",
      phone_number_length: 10,
    },
    {
      name: "Kuwait",
      flag: "🇰🇼",
      code: "KW",
      dial_code: "+965",
      phone_number_length: 8,
    },
    {
      name: "Kyrgyzstan",
      flag: "🇰🇬",
      code: "KG",
      dial_code: "+996",
      phone_number_length: 9,
    },
    {
      name: "Laos",
      flag: "🇱🇦",
      code: "LA",
      dial_code: "+856",
      phone_number_length: 8,
    },
    {
      name: "Latvia",
      flag: "🇱🇻",
      code: "LV",
      dial_code: "+371",
      phone_number_length: 8,
    },
    {
      name: "Lebanon",
      flag: "🇱🇧",
      code: "LB",
      dial_code: "+961",
      phone_number_length: 8,
    },
    {
      name: "Lesotho",
      flag: "🇱🇸",
      code: "LS",
      dial_code: "+266",
      phone_number_length: 8,
    },
    {
      name: "Liberia",
      flag: "🇱🇸",
      code: "LR",
      dial_code: "+231",
      phone_number_length: 8,
    },
    {
      name: "Libya",
      flag: "🇱🇾",
      code: "LY",
      dial_code: "+218",
      phone_number_length: 9,
    },
    {
      name: "Liechtenstein",
      flag: "🇱🇮",
      code: "LI",
      dial_code: "+423",
      phone_number_length: 8,
    },
    {
      name: "Lithuania",
      flag: "🇱🇹",
      code: "LT",
      dial_code: "+370",
      phone_number_length: 8,
    },
    {
      name: "Madagascar",
      flag: "🇲🇬",
      code: "MG",
      dial_code: "+261",
      phone_number_length: 9,
    },
    {
      name: "Malawi",
      flag: "🇲🇼",
      code: "MW",
      dial_code: "+265",
      phone_number_length: 9,
    },
    {
      name: "Malaysia",
      flag: "🇲🇾",
      code: "MY",
      dial_code: "+60",
      phone_number_length: 10,
    },
    {
      name: "Maldives",
      flag: "🇲🇻",
      code: "MV",
      dial_code: "+960",
      phone_number_length: 7,
    },
    {
      name: "Mali",
      flag: "🇲🇱",
      code: "ML",
      dial_code: "+223",
      phone_number_length: 8,
    },
    {
      name: "Malta",
      flag: "🇲🇹",
      code: "MT",
      dial_code: "+356",
      phone_number_length: 8,
    },
    {
      name: "Marshall Islands",
      flag: "🇲🇭",
      code: "MH",
      dial_code: "+692",
      phone_number_length: 7,
    },
    {
      name: "Mauritania",
      flag: "🇲🇷",
      code: "MR",
      dial_code: "+222",
      phone_number_length: 9,
    },
    {
      name: "Mauritius",
      flag: "🇲🇺",
      code: "MU",
      dial_code: "+230",
      phone_number_length: 8,
    },
    {
      name: "Mexico",
      flag: "🇲🇽",
      code: "MX",
      dial_code: "+52",
      phone_number_length: 10,
    },
    {
      name: "Micronesia",
      flag: "🇫🇲",
      code: "FM",
      dial_code: "+691",
      phone_number_length: 7,
    },
    {
      name: "Moldova",
      flag: "🇲🇩",
      code: "MD",
      dial_code: "+373",
      phone_number_length: 8,
    },
    {
      name: "Monaco",
      flag: "🇲🇨",
      code: "MC",
      dial_code: "+377",
      phone_number_length: 8,
    },
    {
      name: "Mongolia",
      flag: "🇲🇳",
      code: "MN",
      dial_code: "+976",
      phone_number_length: 8,
    },
    {
      name: "Montenegro",
      flag: "🇲🇪",
      code: "ME",
      dial_code: "+382",
      phone_number_length: 8,
    },
    {
      name: "Morocco",
      flag: "🇲🇦",
      code: "MA",
      dial_code: "+212",
      phone_number_length: 9,
    },
    {
      name: "Mozambique",
      flag: "🇲🇿",
      code: "MZ",
      dial_code: "+258",
      phone_number_length: 9,
    },
    {
      name: "Namibia",
      flag: "🇳🇦",
      code: "NA",
      dial_code: "+264",
      phone_number_length: 9,
    },
    {
      name: "Nauru",
      flag: "🇳🇷",
      code: "NR",
      dial_code: "+674",
      phone_number_length: 7,
    },
    {
      name: "Nepal",
      flag: "🇳🇵",
      code: "NP",
      dial_code: "+977",
      phone_number_length: 10,
    },
    {
      name: "Netherlands",
      flag: "🇳🇱",
      code: "NL",
      dial_code: "+31",
      phone_number_length: 9,
    },
    {
      name: "New Zealand",
      flag: "🇳🇿",
      code: "NZ",
      dial_code: "+64",
      phone_number_length: 9,
    },
    {
      name: "Nicaragua",
      flag: "🇳🇮",
      code: "NI",
      dial_code: "+505",
      phone_number_length: 8,
    },
    {
      name: "Niger",
      flag: "🇳🇬",
      code: "NE",
      dial_code: "+227",
      phone_number_length: 8,
    },
    {
      name: "Nigeria",
      flag: "🇳🇬",
      code: "NG",
      dial_code: "+234",
      phone_number_length: 10,
    },
    {
      name: "Niue",
      flag: "🇳🇺",
      code: "NU",
      dial_code: "+683",
      phone_number_length: 7,
    },
    {
      name: "Norfolk Island",
      flag: "🇳🇫",
      code: "NF",
      dial_code: "+672",
      phone_number_length: 7,
    },
    {
      name: "North Macedonia",
      flag: "🇲🇰",
      code: "MK",
      dial_code: "+389",
      phone_number_length: 8,
    },
    {
      name: "Northern Mariana Islands",
      flag: "🇲🇵",
      code: "MP",
      dial_code: "+1-670",
      phone_number_length: 7,
    },
    {
      name: "Norway",
      flag: "🇳🇴",
      code: "NO",
      dial_code: "+47",
      phone_number_length: 8,
    },
    {
      name: "Oman",
      flag: "🇴🇲",
      code: "OM",
      dial_code: "+968",
      phone_number_length: 8,
    },
    {
      name: "Pakistan",
      flag: "🇵🇰",
      code: "PK",
      dial_code: "+92",
      phone_number_length: 10,
    },
    {
      name: "Palau",
      flag: "🇵🇼",
      code: "PW",
      dial_code: "+680",
      phone_number_length: 7,
    },
    {
      name: "Panama",
      flag: "🇵🇦",
      code: "PA",
      dial_code: "+507",
      phone_number_length: 8,
    },
    {
      name: "Papua New Guinea",
      flag: "🇵🇬",
      code: "PG",
      dial_code: "+675",
      phone_number_length: 9,
    },
    {
      name: "Paraguay",
      flag: "🇵🇾",
      code: "PY",
      dial_code: "+595",
      phone_number_length: 9,
    },
    {
      name: "Peru",
      flag: "🇵🇪",
      code: "PE",
      dial_code: "+51",
      phone_number_length: 9,
    },
    {
      name: "Philippines",
      flag: "🇵🇭",
      code: "PH",
      dial_code: "+63",
      phone_number_length: 10,
    },
    {
      name: "Pitcairn Islands",
      flag: "🇵🇬",
      code: "PN",
      dial_code: "+64",
      phone_number_length: 7,
    },
    {
      name: "Poland",
      flag: "🇵🇱",
      code: "PL",
      dial_code: "+48",
      phone_number_length: 9,
    },
    {
      name: "Portugal",
      flag: "🇵🇹",
      code: "PT",
      dial_code: "+351",
      phone_number_length: 9,
    },
    {
      name: "Qatar",
      flag: "🇶🇦",
      code: "QA",
      dial_code: "+974",
      phone_number_length: 8,
    },
    {
      name: "Romania",
      flag: "🇷🇴",
      code: "RO",
      dial_code: "+40",
      phone_number_length: 9,
    },
    {
      name: "Russia",
      flag: "🇷🇺",
      code: "RU",
      dial_code: "+7",
      phone_number_length: 10,
    },
    {
      name: "Rwanda",
      flag: "🇷🇼",
      code: "RW",
      dial_code: "+250",
      phone_number_length: 9,
    },
    {
      name: "Saint Kitts and Nevis",
      flag: "🇰🇳",
      code: "KN",
      dial_code: "+1-869",
      phone_number_length: 7,
    },
    {
      name: "Saint Lucia",
      flag: "🇱🇨",
      code: "LC",
      dial_code: "+1-758",
      phone_number_length: 7,
    },
    {
      name: "Saint Vincent and the Grenadines",
      flag: "🇻🇨",
      code: "VC",
      dial_code: "+1-784",
      phone_number_length: 7,
    },
    {
      name: "Samoa",
      flag: "🇼🇸",
      code: "WS",
      dial_code: "+685",
      phone_number_length: 7,
    },
    {
      name: "San Marino",
      flag: "🇸🇲",
      code: "SM",
      dial_code: "+378",
      phone_number_length: 8,
    },
    {
      name: "Sao Tome and Principe",
      flag: "🇸🇹",
      code: "ST",
      dial_code: "+239",
      phone_number_length: 8,
    },
    {
      name: "Saudi Arabia",
      flag: "🇸🇦",
      code: "SA",
      dial_code: "+966",
      phone_number_length: 9,
    },
    {
      name: "Senegal",
      flag: "🇸🇳",
      code: "SN",
      dial_code: "+221",
      phone_number_length: 9,
    },
    {
      name: "Serbia",
      flag: "🇷🇸",
      code: "RS",
      dial_code: "+381",
      phone_number_length: 9,
    },
    {
      name: "Seychelles",
      flag: "🇸🇨",
      code: "SC",
      dial_code: "+248",
      phone_number_length: 7,
    },
    {
      name: "Sierra Leone",
      flag: "🇸🇱",
      code: "SL",
      dial_code: "+232",
      phone_number_length: 8,
    },
    {
      name: "Singapore",
      flag: "🇸🇬",
      code: "SG",
      dial_code: "+65",
      phone_number_length: 8,
    },
    {
      name: "Sint Maarten",
      flag: "🇸🇽",
      code: "SX",
      dial_code: "+1-721",
      phone_number_length: 7,
    },
    {
      name: "Slovakia",
      flag: "🇸🇰",
      code: "SK",
      dial_code: "+421",
      phone_number_length: 9,
    },
    {
      name: "Slovenia",
      flag: "🇸🇮",
      code: "SI",
      dial_code: "+386",
      phone_number_length: 8,
    },
    {
      name: "Solomon Islands",
      flag: "🇸🇧",
      code: "SB",
      dial_code: "+677",
      phone_number_length: 7,
    },
    {
      name: "Somalia",
      flag: "🇸🇴",
      code: "SO",
      dial_code: "+252",
      phone_number_length: 9,
    },
    {
      name: "Taiwan",
      flag: "🇹🇼",
      code: "TW",
      dial_code: "+886",
      phone_number_length: 10,
    },
    {
      name: "Tajikistan",
      flag: "🇹🇯",
      code: "TJ",
      dial_code: "+992",
      phone_number_length: 9,
    },
    {
      name: "Tanzania",
      flag: "🇹🇿",
      code: "TZ",
      dial_code: "+255",
      phone_number_length: 9,
    },
    {
      name: "Thailand",
      flag: "🇹🇭",
      code: "TH",
      dial_code: "+66",
      phone_number_length: 9,
    },
    {
      name: "Timor-Leste",
      flag: "🇹🇱",
      code: "TL",
      dial_code: "+670",
      phone_number_length: 7,
    },
    {
      name: "Togo",
      flag: "🇹🇬",
      code: "TG",
      dial_code: "+228",
      phone_number_length: 8,
    },
    {
      name: "Tokelau",
      flag: "🇹🇰",
      code: "TK",
      dial_code: "+690",
      phone_number_length: 7,
    },
    {
      name: "Tonga",
      flag: "🇹🇴",
      code: "TO",
      dial_code: "+676",
      phone_number_length: 7,
    },
    {
      name: "Trinidad and Tobago",
      flag: "🇹🇹",
      code: "TT",
      dial_code: "+1-868",
      phone_number_length: 7,
    },
    {
      name: "Tunisia",
      flag: "🇹🇳",
      code: "TN",
      dial_code: "+216",
      phone_number_length: 8,
    },
    {
      name: "Turkey",
      flag: "🇹🇷",
      code: "TR",
      dial_code: "+90",
      phone_number_length: 10,
    },
    {
      name: "Turkmenistan",
      flag: "🇹🇲",
      code: "TM",
      dial_code: "+993",
      phone_number_length: 9,
    },
    {
      name: "Tuvalu",
      flag: "🇹🇻",
      code: "TV",
      dial_code: "+688",
      phone_number_length: 7,
    },
    {
      name: "Uganda",
      flag: "🇺🇬",
      code: "UG",
      dial_code: "+256",
      phone_number_length: 9,
    },
    {
      name: "Ukraine",
      flag: "🇺🇦",
      code: "UA",
      dial_code: "+380",
      phone_number_length: 9,
    },
    {
      name: "United Arab Emirates",
      flag: "🇦🇪",
      code: "AE",
      dial_code: "+971",
      phone_number_length: 9,
    },
    {
      name: "United Kingdom",
      flag: "🇬🇧",
      code: "GB",
      dial_code: "+44",
      phone_number_length: 10,
    },
    {
      name: "United States",
      flag: "🇺🇸",
      code: "US",
      dial_code: "+1",
      phone_number_length: 10,
    },
    {
      name: "Uruguay",
      flag: "🇺🇾",
      code: "UY",
      dial_code: "+598",
      phone_number_length: 8,
    },
    {
      name: "Uzbekistan",
      flag: "🇺🇿",
      code: "UZ",
      dial_code: "+998",
      phone_number_length: 9,
    },
    {
      name: "Vanuatu",
      flag: "🇻🇺",
      code: "VU",
      dial_code: "+678",
      phone_number_length: 7,
    },
    {
      name: "Vatican City",
      flag: "🇻🇦",
      code: "VA",
      dial_code: "+379",
      phone_number_length: 8,
    },
    {
      name: "Venezuela",
      flag: "🇻🇪",
      code: "VE",
      dial_code: "+58",
      phone_number_length: 10,
    },
    {
      name: "Vietnam",
      flag: "🇻🇳",
      code: "VN",
      dial_code: "+84",
      phone_number_length: 10,
    },
    {
      name: "Wallis and Futuna",
      flag: "🇼🇫",
      code: "WF",
      dial_code: "+681",
      phone_number_length: 7,
    },
    {
      name: "Western Sahara",
      flag: "🇪🇭",
      code: "EH",
      dial_code: "+212",
      phone_number_length: 9,
    },
    {
      name: "Yemen",
      flag: "🇾🇪",
      code: "YE",
      dial_code: "+967",
      phone_number_length: 9,
    },
    {
      name: "Zambia",
      flag: "🇿🇲",
      code: "ZM",
      dial_code: "+260",
      phone_number_length: 9,
    },
    {
      name: "Zimbabwe",
      flag: "🇿🇼",
      code: "ZW",
      dial_code: "+263",
      phone_number_length: 9,
    },
  ];
  